/**
 * Single source of truth for the public demo account and the creator identity.
 *
 * These are intentionally NOT secrets:
 *  - the demo credentials are printed on the sign-in page for visitors to use
 *  - the creator email only toggles which UI widgets are visible
 * Actual protection comes from Supabase RLS and the server-side `demo_editable`
 * check in the edge functions.
 *
 * Env vars win when present so a deployment can override them; the fallbacks
 * keep the demo prefill working when `.env` is regenerated by the Supabase
 * connection (which strips custom keys).
 */

const env = import.meta.env;

export const DEMO_EMAIL = (env.VITE_DEMO_EMAIL || 'user@yopmail.com').toLowerCase();
export const DEMO_PASSWORD = env.VITE_DEMO_PASSWORD || 'userAssets@123';
export const CREATOR_EMAIL = (
  env.VITE_CREATOR_EMAIL || 'ashdeveloper8@gmail.com'
).toLowerCase();
