// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list_particulars.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.23.8";

// src/lib/mcp/lib/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.52.0";
function supabaseForUser(ctx) {
  const env = globalThis.process?.env ?? {};
  const url = env.SUPABASE_URL;
  const key = env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY;
  if (!url || !key) throw new Error("Supabase env not configured");
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function requireAuth(ctx) {
  if (!ctx.isAuthenticated()) {
    return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
  }
  return null;
}

// src/lib/mcp/lib/encryption.ts
var ENC_PREFIX = "enc:v1:";
var cachedKey = null;
async function getKey() {
  if (cachedKey) return cachedKey;
  const raw = globalThis.process?.env?.AMOUNT_ENCRYPTION_KEY ?? "";
  if (!raw) throw new Error("AMOUNT_ENCRYPTION_KEY is not configured");
  const material = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(raw));
  cachedKey = await crypto.subtle.importKey("raw", material, { name: "AES-GCM" }, false, [
    "encrypt",
    "decrypt"
  ]);
  return cachedKey;
}
function toB64(bytes) {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}
function fromB64(b64) {
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
async function encryptNumber(value) {
  const key = await getKey();
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ct = new Uint8Array(
    await crypto.subtle.encrypt(
      { name: "AES-GCM", iv },
      key,
      new TextEncoder().encode(String(value))
    )
  );
  return `${ENC_PREFIX}${toB64(iv)}:${toB64(ct)}`;
}
async function decryptNumber(stored) {
  if (stored === null || stored === void 0 || stored === "") return 0;
  if (typeof stored === "number") return stored;
  if (!stored.startsWith(ENC_PREFIX)) {
    const n = Number(stored);
    return Number.isFinite(n) ? n : 0;
  }
  const [, , ivB64, ctB64] = stored.split(":");
  if (!ivB64 || !ctB64) return 0;
  try {
    const key = await getKey();
    const pt = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: fromB64(ivB64) },
      key,
      fromB64(ctB64)
    );
    const n = Number(new TextDecoder().decode(pt));
    return Number.isFinite(n) ? n : 0;
  } catch {
    return 0;
  }
}
async function decryptRecord(row) {
  const fields = ["amount", "cash", "investment", "current_value"];
  for (const f of fields) {
    if (f in row) row[f] = await decryptNumber(row[f]);
  }
  return row;
}

// src/lib/mcp/tools/list_particulars.ts
var list_particulars_default = defineTool({
  name: "list_particulars",
  title: "List financial particulars",
  description: "List the signed-in user's financial particulars (assets/entries). Optionally filter by month and year, and cap the result count.",
  inputSchema: {
    month: z.string().optional().describe("Month name filter, e.g. 'Jan'."),
    year: z.number().int().optional().describe("Year filter, e.g. 2026."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ month, year, limit }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    let q = supabaseForUser(ctx).from("financial_particulars").select("*").eq("user_id", ctx.getUserId()).order("date_added", { ascending: false }).limit(limit ?? 100);
    if (month) q = q.eq("month", month);
    if (year) q = q.eq("year", year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = await Promise.all((data ?? []).map((r) => decryptRecord(r)));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/get_stats.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_stats_default = defineTool2({
  name: "get_stats",
  title: "Get portfolio statistics",
  description: "Aggregate the signed-in user's financial particulars: total amount, cash, investment, entry count, per-category breakdown, and average.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const { data, error } = await supabaseForUser(ctx).from("financial_particulars").select("category, amount, cash, investment").eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = await Promise.all(
      (data ?? []).map(async (item) => ({
        category: item.category,
        amount: await decryptNumber(item.amount),
        cash: await decryptNumber(item.cash),
        investment: await decryptNumber(item.investment)
      }))
    );
    const total_amount = rows.reduce((s, r) => s + r.amount, 0);
    const total_cash = rows.reduce((s, r) => s + r.cash, 0);
    const total_investment = rows.reduce((s, r) => s + r.investment, 0);
    const category_breakdown = {};
    for (const r of rows) category_breakdown[r.category] = (category_breakdown[r.category] ?? 0) + r.amount;
    const stats = {
      total_amount,
      total_cash,
      total_investment,
      total_entries: rows.length,
      category_breakdown,
      average_amount: rows.length ? total_amount / rows.length : 0
    };
    return {
      content: [{ type: "text", text: JSON.stringify(stats, null, 2) }],
      structuredContent: stats
    };
  }
});

// src/lib/mcp/tools/create_particular.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.23.8";
var sanitize = (t) => t.replace(/[<>"']/g, "");
var create_particular_default = defineTool3({
  name: "create_particular",
  title: "Create financial particular",
  description: "Insert a new financial particular for the signed-in user. Monetary values are encrypted at rest.",
  inputSchema: {
    category: z2.string().trim().min(1).max(50),
    description: z2.string().trim().max(500).optional(),
    amount: z2.number().positive(),
    cash: z2.number().min(0).optional(),
    investment: z2.number().min(0).optional(),
    current_value: z2.number().min(0).optional(),
    month: z2.string().trim().max(20).optional(),
    month_number: z2.number().int().min(1).max(12).optional(),
    year: z2.number().int().min(1900).max(2100).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const { data, error } = await supabaseForUser(ctx).from("financial_particulars").insert({
      user_id: ctx.getUserId(),
      category: sanitize(input.category),
      description: input.description ? sanitize(input.description) : null,
      amount: await encryptNumber(input.amount),
      cash: await encryptNumber(input.cash ?? 0),
      investment: await encryptNumber(input.investment ?? 0),
      current_value: await encryptNumber(input.current_value ?? 0),
      month: input.month ? sanitize(input.month) : null,
      month_number: input.month_number ?? null,
      year: input.year ?? (/* @__PURE__ */ new Date()).getFullYear()
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const row = data ? await decryptRecord(data) : data;
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: { row }
    };
  }
});

// src/lib/mcp/tools/update_particular.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.23.8";
var sanitize2 = (t) => t.replace(/[<>"']/g, "");
var update_particular_default = defineTool4({
  name: "update_particular",
  title: "Update financial particular",
  description: "Update an existing financial particular by id for the signed-in user.",
  inputSchema: {
    id: z3.string().uuid(),
    category: z3.string().trim().min(1).max(50).optional(),
    description: z3.string().trim().max(500).optional(),
    amount: z3.number().positive().optional(),
    cash: z3.number().min(0).optional(),
    investment: z3.number().min(0).optional(),
    current_value: z3.number().min(0).optional(),
    month: z3.string().trim().max(20).optional(),
    month_number: z3.number().int().min(1).max(12).optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ id, ...input }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const updates = {};
    if (input.category !== void 0) updates.category = sanitize2(input.category);
    if (input.description !== void 0) updates.description = sanitize2(input.description);
    if (input.month !== void 0) updates.month = sanitize2(input.month);
    if (input.month_number !== void 0) updates.month_number = input.month_number;
    if (typeof input.amount === "number") updates.amount = await encryptNumber(input.amount);
    if (typeof input.cash === "number") updates.cash = await encryptNumber(input.cash);
    if (typeof input.investment === "number") updates.investment = await encryptNumber(input.investment);
    if (typeof input.current_value === "number") updates.current_value = await encryptNumber(input.current_value);
    const { data, error } = await supabaseForUser(ctx).from("financial_particulars").update(updates).eq("id", id).eq("user_id", ctx.getUserId()).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const row = data ? await decryptRecord(data) : data;
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: { row }
    };
  }
});

// src/lib/mcp/tools/delete_particular.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.23.8";
var delete_particular_default = defineTool5({
  name: "delete_particular",
  title: "Delete financial particular",
  description: "Delete a financial particular by id for the signed-in user. Irreversible.",
  inputSchema: {
    id: z4.string().uuid()
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  needsApproval: true,
  handler: async ({ id }, ctx) => {
    const guard = requireAuth(ctx);
    if (guard) return guard;
    const { error } = await supabaseForUser(ctx).from("financial_particulars").delete().eq("id", id).eq("user_id", ctx.getUserId());
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Deleted ${id}` }],
      structuredContent: { id, deleted: true }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "xkyhvkuahdvvlwjgnipt";
var mcp_default = defineMcp({
  name: "assetpulse-mcp",
  title: "AssetPulse MCP",
  version: "0.1.0",
  instructions: "Tools for AssetPulse \u2014 a personal finance / assets tracker. Use `list_particulars` and `get_stats` to read the signed-in user's portfolio. Use `create_particular`, `update_particular`, and `delete_particular` to modify entries. Monetary values are encrypted at rest and returned as decrypted numbers.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_particulars_default,
    get_stats_default,
    create_particular_default,
    update_particular_default,
    delete_particular_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
